"use client";
import { useEffect, useState } from "react";
import { fetchJson } from "@/lib/fetch-json";
import { EmptyState } from "@/components/ui/EmptyState";
import { ErrorBanner } from "@/components/ui/ErrorBanner";

type WeeklyDigest = {
  id: string;
  weekStart: string;
  weekEnd: string;
  summaryText: string;
  stats: {
    documentsProcessed: number;
    tasksCompleted: number;
    tasksOverdue: number;
    conversationsStarted: number;
  };
  createdAt: string;
};

// No create form on this page, digests are only generated by digest-worker.ts on its weekly schedule, this page just reads the history.
export default function DigestPage() {
  const [digests, setDigests] = useState<WeeklyDigest[] | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    (async () => {
      try {
        const list = await fetchJson<WeeklyDigest[]>("/api/digests");
        setDigests(list);
      } catch (err) {
        setError(err instanceof Error ? err.message : "Couldn't load the digest list");
      }
    })();
  }, []);

  return (
    <div>
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Weekly digest</h1>
        <p className="text-sm text-gray-500 dark:text-gray-400">
          The AI automatically summarizes your activity every week, documents, tasks, conversations.
        </p>
      </div>

      {error && <ErrorBanner message={error} />}

      {digests === null && <p className="text-sm text-gray-400 dark:text-gray-500">Loading...</p>}
      {digests !== null && digests.length === 0 && (
        <EmptyState
          title="No digests yet"
          description="Your first digest will appear after a full week of activity."
        />
      )}

      <div className="flex flex-col gap-4">
        {digests?.map((d) => (
          <div
            key={d.id}
            className="rounded-2xl border-l-2 border-indigo-600 bg-white p-5 shadow-soft dark:bg-gray-900"
          >
            <div className="mb-2 flex items-center justify-between gap-2">
              <p className="text-xs font-semibold text-indigo-600 dark:text-indigo-400">AI Knowledge Assistant</p>
              <span className="text-xs text-gray-400 dark:text-gray-500">
                {new Date(d.weekStart).toLocaleDateString("en-US")} – {new Date(d.weekEnd).toLocaleDateString("en-US")}
              </span>
            </div>
            <p className="text-sm text-gray-800 dark:text-gray-100">{d.summaryText}</p>
            <div className="mt-3 flex flex-wrap gap-2 text-xs">
              {d.stats.documentsProcessed > 0 && (
                <span className="rounded-full bg-gray-100 px-2 py-0.5 text-gray-600 dark:bg-gray-800 dark:text-gray-300">
                  {d.stats.documentsProcessed} documents
                </span>
              )}
              {d.stats.tasksCompleted > 0 && (
                <span className="rounded-full bg-gray-100 px-2 py-0.5 text-gray-600 dark:bg-gray-800 dark:text-gray-300">
                  {d.stats.tasksCompleted} tasks completed
                </span>
              )}
              {d.stats.tasksOverdue > 0 && (
                <span className="rounded-full bg-red-50 px-2 py-0.5 text-red-600 dark:bg-red-500/10 dark:text-red-300">
                  {d.stats.tasksOverdue} tasks overdue
                </span>
              )}
              {d.stats.conversationsStarted > 0 && (
                <span className="rounded-full bg-gray-100 px-2 py-0.5 text-gray-600 dark:bg-gray-800 dark:text-gray-300">
                  {d.stats.conversationsStarted} new conversations
                </span>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
